variables:
  azureSubscription: 'AZR-RWD-PRD1'
  docker.imageName: 'producervalidation'
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: 'producervalidationrepository'
  serviceName: 'prdrwdwebfa1402'
